Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

# Set Pandas floating point display precision.
pd.set_option("precision", 2)

# Class colors
COLORS = "rgba(255, 0, 0, 0.3)", "rgba(0, 255, 0, 0.3)", "rgba(0, 0, 255, 0.3)"

# Create a unified dataframe.
data = pd.concat([X, y], axis="columns")


# Set class background color
def set_class_color(class_index: str) -> str:
    return f"background-color: {COLORS[class_index]};"


def set_class_name(class_index: str) -> str:
    return iris_dataset.target_names[class_index]


# Select some sample indices
sample_indices = np.linspace(0, len(data) - 5, 3, dtype=int)
sample_indices = [index for i in sample_indices for index in range(i, i + 5)]

# Display table
data.iloc[sample_indices, :].style.background_gradient().applymap(
    set_class_color,
    subset=[TARGET_NAME]).format(set_class_name, subset=[
        TARGET_NAME
    ]).set_properties(**{
        "border": "1px solid black"
    }, subset=[TARGET_NAME]).set_properties(**{
        "text-align": "center"
    }).set_table_styles([
        dict(selector="th", props=[("font-size", "14px")]),
        dict(selector="td", props=[("font-size", "12px")]),
    ])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOptionError[0m                               Traceback (most recent call last)
Cell [0;32mIn[3], line 4[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      3[0m [38;5;66;03m# Set Pandas floating point display precision.[39;00m
[0;32m----> 4[0m [43mpd[49m[38;5;241;43m.[39;49m[43mset_option[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mprecision[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;241;43m2[39;49m[43m)[49m
[1;32m      6[0m [38;5;66;03m# Class colors[39;00m
[1;32m      7[0m COLORS [38;5;241m=[39m [38;5;124m"[39m[38;5;124mrgba(255, 0, 0, 0.3)[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mrgba(0, 255, 0, 0.3)[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mrgba(0, 0, 255, 0.3)[39m[38;5;124m"[39m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pandas/_config/config.py:272[0m, in [0;36mCallableDynamicDoc.__call__[0;34m(self, *args, **kwds)[0m
[1;32m    271[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds) [38;5;241m-[39m[38;5;241m>[39m T:
[0;32m--> 272[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[38;5;18;43m__func__[39;49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pandas/_config/config.py:167[0m, in [0;36m_set_option[0;34m(*args, **kwargs)[0m
[1;32m    164[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124m_set_option() got an unexpected keyword argument [39m[38;5;124m"[39m[38;5;132;01m{[39;00mkwarg[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m'[39m)
[1;32m    166[0m [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28mzip[39m(args[::[38;5;241m2[39m], args[[38;5;241m1[39m::[38;5;241m2[39m]):
[0;32m--> 167[0m     key [38;5;241m=[39m [43m_get_single_key[49m[43m([49m[43mk[49m[43m,[49m[43m [49m[43msilent[49m[43m)[49m
[1;32m    169[0m     o [38;5;241m=[39m _get_registered_option(key)
[1;32m    170[0m     [38;5;28;01mif[39;00m o [38;5;129;01mand[39;00m o[38;5;241m.[39mvalidator:

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pandas/_config/config.py:134[0m, in [0;36m_get_single_key[0;34m(pat, silent)[0m
[1;32m    132[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such keys(s): [39m[38;5;132;01m{[39;00m[38;5;28mrepr[39m(pat)[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    133[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(keys) [38;5;241m>[39m [38;5;241m1[39m:
[0;32m--> 134[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124m"[39m[38;5;124mPattern matched multiple keys[39m[38;5;124m"[39m)
[1;32m    135[0m key [38;5;241m=[39m keys[[38;5;241m0[39m]
[1;32m    137[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m silent:

[0;31mOptionError[0m: Pattern matched multiple keys

