Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from plots.pca_scatter import plot_reduced


y_iris_labels = y_iris.replace({"setosa": 0, "versicolor": 1, "virginica": 2}).values

plot_reduced(X_iris_reduced, y_iris_labels)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mplots[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpca_scatter[39;00m [38;5;28;01mimport[39;00m plot_reduced
[1;32m      4[0m y_iris_labels [38;5;241m=[39m y_iris[38;5;241m.[39mreplace({[38;5;124m"[39m[38;5;124msetosa[39m[38;5;124m"[39m: [38;5;241m0[39m, [38;5;124m"[39m[38;5;124mversicolor[39m[38;5;124m"[39m: [38;5;241m1[39m, [38;5;124m"[39m[38;5;124mvirginica[39m[38;5;124m"[39m: [38;5;241m2[39m})[38;5;241m.[39mvalues
[1;32m      6[0m plot_reduced(X_iris_reduced, y_iris_labels)

File [0;32m~/work/ml_for_neuro/ml_for_neuro/ml_for_neuro/chapters/chapter_08/plots/pca_scatter.py:3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m interact
[1;32m      5[0m DEFAULT_TITLE [38;5;241m=[39m [38;5;124m"[39m[38;5;124mDataset Projected Over [39m[38;5;132;01m{n_dimensions}[39;00m[38;5;124m Dimensions Using PCA[39m[38;5;124m"[39m
[1;32m      6[0m PCA_AXIS_LABELS_2D [38;5;241m=[39m {
[1;32m      7[0m     [38;5;124m"[39m[38;5;124mxlabel[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mPrincipal Component #1[39m[38;5;124m"[39m,
[1;32m      8[0m     [38;5;124m"[39m[38;5;124mylabel[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mPrincipal Component #2[39m[38;5;124m"[39m,
[1;32m      9[0m }

[0;31mModuleNotFoundError[0m: No module named 'ipywidgets'

